include:
  - project: theplenkov-npm/npm-cicd
    file: /typescript/.gitlab-ci.yml

stages:
  - test:node
  - test:cli
  - deploy

test:collection:build:
  stage: test:node
  extends: .ts
  script:
    - mkdir test/results
    - npm run test:collection
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - test/results

test:collection:run:
  image:
    name: postman/newman
    entrypoint: [""]
  stage: test:cli
  script:
    - newman run test/results/postman-echo.collection.json --globals test/results/postman-echo.globals.json
  needs: ["test:collection:build"]

test:newman:
  extends: .ts
  stage: test:node
  script:
    - npm run test:newman

publish:
  needs: ["test:newman"]
