include:
  - project: theplenkov-npm/npm-cicd
    file: /typescript/.gitlab-ci.yml

stages:
  - test
  - deploy

test:collection:build:
  stage: test
  extends: .ts
  script:
    - npm run test:collection
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - test/results

test:collection:run:
  image: postman/newman
  stage: test
  script:
    - run test/results/postman-echo.collection.json
  dependencies:
    - test:collection:build

test:newman:
  extends: .ts
  stage: test
  script:
    - npm run test:newman
